version: '3'
services:
  multi-cli-gcloud:
    build: ./gcloud/
    container_name: multi-cli-gcloud
    tty: true
    volumes:
      - ./gcloud:/home/gcloud
  multi-cli-azure:
    build: ./azure/
    container_name: multi-cli-azure
    tty: true
    volumes:
      - ./azure:/home/azure
  multi-cli-aws:
    build: ./aws/
    container_name: multi-cli-aws
    tty: true
    volumes:
      - ./aws:/home/aws
