version: '3'
services:
  gcloud:
    build: ./gcloud/
    container_name: multi-cli-gcloud
    tty: true
    volumes:
      - ./gcloud:/home/gcloud
  azure:
    build: ./azure/
    container_name: multi-cli-azure
    tty: true
    volumes:
      - ./azure:/home/azure
  aws:
    build: ./aws/
    container_name: multi-cli-aws
    tty: true
    volumes:
      - ./aws:/home/aws
