ARG _TAG='2.1.13'
FROM aws-cli:${_TAG}
# Tag List --> https://hub.docker.com/r/amazon/aws-cli/tags?ordering=last_updated



# RUN apk -v --update add \
#         python \
#         py-pip \
#         groff \
#         less \
#         mailcap \
#         && \
#     pip install --upgrade awscli==${_TAG} s3cmd==2.0.1 python-magic && \
#     apk -v --purge del py-pip && \
#     rm /var/cache/apk/*
# VOLUME /root/.aws
# VOLUME /project
# WORKDIR /home/aws


